# Generated by Django 2.2.5 on 2019-10-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customernumber', models.TextField(db_column='customerNumber', primary_key=True, serialize=False)),
                ('customername', models.TextField(blank=True, db_column='customerName', null=True)),
                ('contactlastname', models.TextField(blank=True, db_column='contactLastName', null=True)),
                ('contactfirstname', models.TextField(blank=True, db_column='contactFirstName', null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('addressline1', models.TextField(blank=True, db_column='addressLine1', null=True)),
                ('addressline2', models.TextField(blank=True, db_column='addressLine2', null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('postalcode', models.TextField(blank=True, db_column='postalCode', null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('salesrepemployeenumber', models.TextField(blank=True, db_column='salesRepEmployeeNumber', null=True)),
                ('creditlimit', models.TextField(blank=True, db_column='creditLimit', null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeenumber', models.TextField(db_column='employeeNumber', primary_key=True, serialize=False)),
                ('lastname', models.TextField(blank=True, db_column='lastName', null=True)),
                ('firstname', models.TextField(blank=True, db_column='firstName', null=True)),
                ('extension', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('officecode', models.TextField(blank=True, db_column='officeCode', null=True)),
                ('reportsto', models.TextField(blank=True, db_column='reportsTo', null=True)),
                ('jobtitle', models.TextField(blank=True, db_column='jobTitle', null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('officecode', models.TextField(db_column='officeCode', primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('addressline1', models.TextField(blank=True, db_column='addressLine1', null=True)),
                ('addressline2', models.TextField(blank=True, db_column='addressLine2', null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('postalcode', models.TextField(blank=True, db_column='postalCode', null=True)),
                ('territory', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.TextField(blank=True, db_column='orderNumber', null=True)),
                ('productcode', models.TextField(blank=True, db_column='productCode', null=True)),
                ('quantityordered', models.TextField(blank=True, db_column='quantityOrdered', null=True)),
                ('priceeach', models.TextField(blank=True, db_column='priceEach', null=True)),
                ('orderlinenumber', models.TextField(blank=True, db_column='orderLineNumber', null=True)),
            ],
            options={
                'db_table': 'orderdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ordernumber', models.TextField(db_column='orderNumber', primary_key=True, serialize=False)),
                ('orderdate', models.TextField(blank=True, db_column='orderDate', null=True)),
                ('requireddate', models.TextField(blank=True, db_column='requiredDate', null=True)),
                ('shippeddate', models.TextField(blank=True, db_column='shippedDate', null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('customernumber', models.TextField(blank=True, db_column='customerNumber', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('customernumber', models.TextField(blank=True, db_column='customerNumber', null=True)),
                ('checknumber', models.TextField(db_column='checkNumber', primary_key=True, serialize=False)),
                ('paymentdate', models.TextField(blank=True, db_column='paymentDate', null=True)),
                ('amount', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productlines',
            fields=[
                ('productline', models.TextField(db_column='productLine', primary_key=True, serialize=False)),
                ('textdescription', models.TextField(blank=True, db_column='textDescription', null=True)),
                ('htmldescription', models.TextField(blank=True, db_column='htmlDescription', null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productlines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productcode', models.TextField(db_column='productCode', primary_key=True, serialize=False)),
                ('productname', models.TextField(blank=True, db_column='productName', null=True)),
                ('productline', models.TextField(blank=True, db_column='productLine', null=True)),
                ('productscale', models.TextField(blank=True, db_column='productScale', null=True)),
                ('productvendor', models.TextField(blank=True, db_column='productVendor', null=True)),
                ('productdescription', models.TextField(blank=True, db_column='productDescription', null=True)),
                ('quantityinstock', models.TextField(blank=True, db_column='quantityInStock', null=True)),
                ('buyprice', models.TextField(blank=True, db_column='buyPrice', null=True)),
                ('msrp', models.TextField(blank=True, db_column='MSRP', null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
