# Generated by Django 2.2.5 on 2019-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discountcode',
            fields=[
                ('code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('exp', models.DateField()),
                ('qty', models.IntegerField()),
            ],
            options={
                'db_table': 'discountcode',
                'managed': False,
            },
        ),
    ]
